language: java
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash mvn clean integration-test -Pci -DSAUCELABS_USERNAME=$SAUCELABS_USERNAME -DSAUCELABS_ACCESSKEY=$SAUCELABS_ACCESSKEY -DbuildNumber=$TRAVIS_BUILD_NUMBER; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash mvn clean install -DskipTest=true; fi'
